import type { Metadata } from "next";
import { Container } from "@/components/ui/container";
import { BusinessCalculator } from "@/components/business/business-calculator";
import { BusinessBenefits } from "@/components/business/business-benefits";
import { BusinessLeadForm } from "@/components/business/business-lead-form";

export const metadata: Metadata = { title: "Canecas para empresas", description: "Canecas personalizadas para equipes, eventos e grandes pedidos com 20% de desconto a partir de 10 unidades." };

export default function BusinessPage() { return <><section className="overflow-hidden bg-[var(--brand-orange)] py-16 text-white sm:py-24"><Container className="grid items-center gap-12 lg:grid-cols-[1.1fr_.9fr]"><div><p className="text-xs font-black uppercase tracking-[.2em] text-white/75">Presentes para empresas</p><h1 className="font-display mt-5 text-[clamp(3.5rem,7vw,6.8rem)] font-black leading-[.84] tracking-[-.075em]">Sua marca em boas mãos.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/80">Para agradecer, receber, celebrar ou reunir. A partir de 10 canecas, sua empresa recebe 20% de desconto automático.</p><a href="#contato-empresarial" className="mt-8 inline-flex min-h-12 items-center rounded-full bg-[var(--brand-black)] px-6 text-sm font-extrabold text-white">Quero fazer um pedido</a></div><BusinessCalculator /></Container></section><Container className="space-y-20 py-20 sm:py-28"><BusinessBenefits /><section className="grid gap-8 border-y border-[var(--brand-border)] py-14 md:grid-cols-3"><div><p className="text-xs font-black uppercase tracking-[.16em] text-[var(--brand-orange-deep)]">Como funciona</p><h2 className="font-display mt-4 text-4xl font-black">Simples do início ao fim.</h2></div>{[{ n: "01", title: "Conte o pedido", copy: "Quantidade, ocasião e ideia." }, { n: "02", title: "Aprove as artes", copy: "Veja cada caneca antes da produção." }, { n: "03", title: "Receba", copy: "Frete e prazo combinados com clareza." }].map((step) => <article key={step.n}><span className="font-display text-2xl font-black text-[var(--brand-orange)]">{step.n}</span><h3 className="mt-4 text-xl font-black">{step.title}</h3><p className="mt-2 text-[var(--brand-muted)]">{step.copy}</p></article>)}</section><BusinessLeadForm /></Container></>; }
